#!/usr/bin/env php
<?php

$autoload = __DIR__.'/vendor/autoload.php';

if (!file_exists($autoload)) {
    exit("\nUnable to load dependencies. Run `composer install` and try again.\n\n");
}

require $autoload;

require_once('config.php');

$app = new \VirX\Qaton\App(APP_NAME . DIRECTORY_SEPARATOR, __DIR__);

$app->setConfig($APP_CONFIG);

$app->run();