#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

require_once('config.php');

$app = new \VirX\Qaton\App(APP_NAME . DIRECTORY_SEPARATOR, __DIR__);

$app->setConfig($APP_CONFIG);

$app->run();